### ISSUE TITLE
What for helpers.php?

### ISSUE THREAD

**Issue by gugglegum** [jfcherng/php-color-output#1]
OOP-style is good for all. This helper.php makes also a memory and performance hit because it autoloads on every run. Even if it's not used but required by some package.

**Comment by jfcherng** [comment]
I liked those global functions in old PHP but PHP world has changed :)

Done in `3.0.0` since it's a huge BC break.
https://github.com/jfcherng/php-color-output/releases/tag/3.0.0

**Comment by gugglegum** [comment]
Thanks!
